name: "Terraform Infrastructure"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init & Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
      run: |
          cd terraform
          terraform init
          # Pehle bucket ko import karne ki koshish karo, agar pehle se hai toh error ignore karo
          terraform import aws_s3_bucket.currency_bucket capstone-currency-data-saud-final-2026 || true
          terraform apply -auto-approve