name: "Terraform Infrastructure"
on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init & Apply
<<<<<<< HEAD
<<<<<<< HEAD
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
=======
        run: |
          echo "Terraform initialized"
>>>>>>> 3f4bde50189bdebe84496db1c44f78c052987af8
=======
        run: |
          echo "Terraform initialized"
>>>>>>> fd711e00b6991d8c07c8896ba470bbfa271be207
